spring.application.name=REPLACE_ME
# ===============================
# = SERVER CONFIG (optional)
# ===============================

server.address=REPLACE_ME
server.port=REPLACE_ME

# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring.datasource.url=REPLACE_ME
spring.datasource.username=REPLACE_ME
spring.datasource.password=REPLACE_ME
spring.datasource.driver-class-name=REPLACE_ME


# ===============================
# = JPA / HIBERNATE CONFIGURATION
# ===============================
# Automatically create / update tables
spring.jpa.hibernate.ddl-auto=REPLACE_ME


# Set dialect for MySQL
spring.jpa.properties.hibernate.dialect=REPLACE_ME

cloudinary.cloud_name=REPLACE_ME
cloudinary.api_key=REPLACE_ME
cloudinary.api_secret=REPLACE_ME
